version: '3.8'

services:
  web:
    image: th3ro/smuzi_frontend:latest
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
      - NEXT_PUBLIC_YANDEX_VERIFICATION=${NEXT_PUBLIC_YANDEX_VERIFICATION}
    ports:
      - '${FRONTEND_PORT}:80'
    restart: always
