version: '3.8'

services:
  web:
    build: 
      context: .
      args:
        DOCKER_BUILDKIT: 1
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    ports:
      - '${FRONTEND_URL}:80'
    restart: always
