export {
  COMPANY_LOGIN_FORM_SCHEMA,
  DEFAULT_FORM_VALUES_COMPANY,
  LOCALSTORAGE_NAME_COMPANY,
} from './company';

export {
  DEFAULT_FORM_VALUES_STUDENT,
  LOCALSTORAGE_NAME_STUDENT,
  STUDENT_LOGIN_FORM_SCHEMA,
} from './student';
