export const DEFAULT_FORM_VALUES = {
  commandName: '',
  studentId: '',
  studentGroupId: '',
  groupId: '',
  firstName: '',
  lastName: '',
  patronymic: '',
  course: 1,
  firstPriority: -1,
  middlePriority: -1,
  lastPriority: -1,
  otherPriority: '',
  telegram: '',
  resumeLink: '',
  resumePDF: undefined,
};
